// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxCjABmecm0ZW4A81O2dASnSyZlsy5MsU',
    appId: '1:253790293160:web:9ed2b8c99fe0b117efc69d',
    messagingSenderId: '253790293160',
    projectId: 'agri-cambodia',
    authDomain: 'agri-cambodia.firebaseapp.com',
    storageBucket: 'agri-cambodia.firebasestorage.app',
    measurementId: 'G-J5PG9EJ1R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGzaqxTXX4PlgDjCkFZhNx0-9c6g5xqmM',
    appId: '1:253790293160:android:0a844a4183e0df00efc69d',
    messagingSenderId: '253790293160',
    projectId: 'agri-cambodia',
    storageBucket: 'agri-cambodia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARKNn2ENjSnK5-DogiFlU1yQtIN-D9_k8',
    appId: '1:253790293160:ios:767f973fe23ac2a3efc69d',
    messagingSenderId: '253790293160',
    projectId: 'agri-cambodia',
    storageBucket: 'agri-cambodia.firebasestorage.app',
    iosBundleId: 'com.example.ag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARKNn2ENjSnK5-DogiFlU1yQtIN-D9_k8',
    appId: '1:253790293160:ios:7b070dba1f8fde7aefc69d',
    messagingSenderId: '253790293160',
    projectId: 'agri-cambodia',
    storageBucket: 'agri-cambodia.firebasestorage.app',
    iosBundleId: 'com.example.',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxCjABmecm0ZW4A81O2dASnSyZlsy5MsU',
    appId: '1:253790293160:web:e800613ee1602772efc69d',
    messagingSenderId: '253790293160',
    projectId: 'agri-cambodia',
    authDomain: 'agri-cambodia.firebaseapp.com',
    storageBucket: 'agri-cambodia.firebasestorage.app',
    measurementId: 'G-QR3WG62JFP',
  );
}
